name: Deploy ASP.NET MVC App deploy to Azure Web App

on:
  push:
    branches:
      - main

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
env:
  AZURE_WEBAPP_NAME: MyMovie                            # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './MyMovie'                # set this to the path to your web app project, defaults to the repository root
  AZURE_WEBAPP_SOLUTION_PATH: './MyMovie/MyMovie.sln'   # set this to the path to your web app project, defaults to the repository root
  NUGET_VERSION: '6.0.x'                                # set this to the dot net version to use
  AZURE_WEBAPP_PUBLISH_PROFILE: secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0C469F10A76E4193A614CEB6DEA2D51D # Includes GitHub secret
  Authentication:Twitter:ConsumerAPIKey: ${{ secrets.GOOGLE_CLIENTID }}                                 # Includes GitHub secret
  Authentication:Google:ClientSecret: ${{ secrets.GOOGLE_CLIENTSECRET }}                                # Includes GitHub secret
  Authentication:Google:ClientId: ${{ secrets.GOOGLE_CONSUMERSECRET }}                                  # Includes GitHub secret
  Authentication:Twitter:ConsumerSecret: ${{ secrets.TWITTER_CONSUMERAPIKEY }}                          # Includes GitHub secret

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:

    # checkout the repo
    - uses: actions/checkout@master  
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
        
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    
    - name: Run MSBuild
      run: msbuild ${{ AZURE_WEBAPP_SOLUTION_PATH }}
       
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/MyMovie/'
