name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
env:
  AZURE_WEBAPP_NAME: MyMovie                       # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './MyMovie'           # set this to the path to your web app project, defaults to the repository root
  #AZURE_WEBAPP_PACKAGE_PATH: './MyMovie/MyMovie'  # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                          # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')
  AZURE_WEBAPP_PUBLISH_PROFILE: secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0C469F10A76E4193A614CEB6DEA2D51D # Includes GitHub secret
  #Authentication:Twitter:ConsumerAPIKey: ${{ secrets.GOOGLE_CLIENTID }}                                 # Includes GitHub secret
  #Authentication:Google:ClientSecret: ${{ secrets.GOOGLE_CLIENTSECRET }}                                # Includes GitHub secret
  #Authentication:Google:ClientId: ${{ secrets.GOOGLE_CONSUMERSECRET }}                                  # Includes GitHub secret
  #Authentication:Twitter:ConsumerSecret: ${{ secrets.TWITTER_CONSUMERAPIKEY }}                          # Includes GitHub secret

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet setup
      - name: dotnet dependencies
        run: dotnet restore
        
      # Run dotnet build
      - name: dotnet build
        run: dotnet restore --no-restore -c Release

      # Run dotnet publish
      - name: dotnet publish
        run: dotnet publish --no-build -c Release -o env.AZURE_WEBAPP_PACKAGE_PATH
        #run: dotnet publish --no-build -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
        
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }} # Define secret variable in repository settings as per action documentation
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          #package: ./MyMovie
          #package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
